version: "3.9"
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_server
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/.chroma  # persistencia local
    environment:
      - ANONYMIZED_TELEMETRY=False
